name: DevOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  code-scan:
    runs-on: ubuntu-latest
    needs: code-checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan on code
        run: |
          trivy fs --exit-code 0 --severity HIGH,CRITICAL --format json --output trivy-code-report.json .

      - name: Upload Trivy code scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-code-report
          path: trivy-code-report.json

  build-and-package:
    runs-on: ubuntu-latest
    needs: code-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "GIT_SHORT_SHA=${GITHUB_SHA::5}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: DevOps-Projects-Masters/GitOpswithKubernetes/application/apps
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/curd-app:latest
            ${{ secrets.DOCKER_USERNAME }}/curd-app:${{ env.GIT_SHORT_SHA }}-${{ github.run_number }}

  docker-image-scan:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan on Docker image
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL --format json --output trivy-docker-report.json ${{ secrets.DOCKER_USERNAME }}/curd-app:${{ env.GIT_SHORT_SHA }}-${{ github.run_number }}

      - name: Upload Trivy Docker image scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-docker-report
          path: trivy-docker-report.json

  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: docker-image-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/curd-app:${{ env.GIT_SHORT_SHA }}-${{ github.run_number }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: push-to-dockerhub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update manifest file
        run: |
          sed -i 's|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/curd-app:${{ env.GIT_SHORT_SHA }}-${{ github.run_number }}|' path/to/manifest/file.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add path/to/manifest/file.yaml
          git commit -m 'Update manifest file with latest Docker image'
          git push origin main