name: tf_deploy_infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform (plan, apply, destroy)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set SSH public key environment variable
        run: echo "SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init
        working-directory: DevOps-Projects-Masters/GitOpswithKubernetes/tf-code

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -var "public_key=$SSH_PUBLIC_KEY"
        working-directory: DevOps-Projects-Masters/GitOpswithKubernetes/tf-code

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve -var "public_key=$SSH_PUBLIC_KEY"
        working-directory: DevOps-Projects-Masters/GitOpswithKubernetes/tf-code

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -var "public_key=$SSH_PUBLIC_KEY"
        working-directory: DevOps-Projects-Masters/GitOpswithKubernetes/tf-code